
import type { Product } from './types';

export const allProducts: Product[] = [
    {
        id: 153756,
        name: "Lote Miss Giordani",
        brand: "Giordani Gold",
        price: 19.24,
        regularPrice: 55.49,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F153756%2F153756_1.png',
        description: "Un set de regalo exclusivo con la fragancia Miss Giordani, que captura la pasión y la sofisticación del estilo de vida italiano en una botella.",
        stock: 20,
        category: 'perfume',
        tag: 'NOVEDAD',
        statusLabel: 'Set',
        rating: 5,
        reviewCount: 1,
    },
    {
        id: 153757,
        name: "Lote Mister Giordani",
        brand: "Giordani Gold",
        price: 19.24,
        regularPrice: 55.49,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F153757%2F153757_1.png',
        description: "Un lote de regalo para hombre con la distintiva fragancia Mister Giordani, una esencia moderna y masculina con la calidad atemporal de Giordani Gold.",
        stock: 18,
        category: 'perfume',
        tag: 'NOVEDAD',
        statusLabel: 'Set',
        rating: 5,
        reviewCount: 1,
    },
    {
        id: 48649,
        name: "Crema Universal Original - Edición Especial",
        brand: "Tender Care",
        price: 5.38,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48649%2F48649_1.png',
        description: "La icónica Crema Universal en una edición especial de regalo. Su fórmula con cera de abeja natural hidrata, suaviza y protege la piel seca y áspera.",
        stock: 100,
        category: 'skincare',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 34,
    },
    {
        id: 47536,
        name: "Crema para Manos y Cuerpo Majestic Magnolia Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 6.92,
        regularPrice: 18.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47536%2F47536_1.png',
        description: "Una lujosa crema para manos y cuerpo enriquecida con extractos de leche y miel y una fragancia de magnolia. Nutre intensamente para una piel suave y radiante.",
        stock: 40,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 21,
    },
    {
        id: 47538,
        name: "Jabón en Barra Majestic Magnolia Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 2.30,
        regularPrice: 6.50,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47538%2F47538_1.png',
        description: "Un jabón en barra cremoso y perfumado con magnolia, leche y miel. Limpia suavemente mientras hidrata, dejando la piel suave y con un aroma exquisito.",
        stock: 80,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 7,
    },
    {
        id: 41058,
        name: "Tratamiento de Día Rico SPF 30 Multi-Active",
        brand: "NovAge+",
        price: 42.00,
        regularPrice: 57.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41058%2F41058_1.png',
        description: "Tratamiento de día rico y ultrahidratante formulado para nutrir intensamente y reponer la piel, a la vez que la protege de los agresores urbanos como la polución y los rayos UV. Con factor de protección solar SPF 30.",
        howToUse: "Aplicar por la mañana sobre la piel limpia. Coger una pequeña cantidad de crema de día con la yema de los dedos y masajear suavemente sobre el rostro y el cuello, evitando el contorno de los ojos.",
        stock: 25,
        category: 'skincare',
        rating: 5,
        reviewCount: 112,
    },
    {
        id: 34897,
        name: "After Sun Jelly para Rostro y Cuerpo Sun 360",
        brand: "Sun 360",
        price: 14.00,
        regularPrice: 17.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F34897%2F34897_1.png',
        description: "Gelatina after sun para rostro y cuerpo que hidrata intensamente y calma la piel al instante después de la exposición al sol hasta 24 horas. Ayuda a prolongar el bronceado.",
        howToUse: "Aplicar generosamente sobre la piel limpia después de la exposición al sol. Masajear suavemente hasta su completa absorción.",
        stock: 40,
        category: 'personal-care',
        rating: 4,
        reviewCount: 78,
    },
    {
        id: 48648,
        name: "Caja de Regalo Crema Universal",
        brand: "Tender Care",
        price: 17.00,
        regularPrice: 19.99,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48648%2F48648_1.png',
        description: "El bálsamo multiusos original con cera de abeja natural y vitamina E, en una caja de regalo con tres variantes: Original, Fruta de la Pasión y Arándano Rojo. Suaviza, calma e hidrata la piel seca.",
        howToUse: "Aplicar sobre la piel seca de rostro, labios, manos, codos, rodillas o pies. Usar tantas veces como sea necesario.",
        stock: 50,
        category: 'skincare',
        rating: 5,
        reviewCount: 210,
    },
     {
        id: 44964,
        name: "Sérum Sellador de Puntas Duologi",
        brand: "DUOLOGI",
        price: 8.49,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44964%2F44964_1.png',
        description: "Sérum transformador de doble acción que sella las puntas abiertas y reduce el encrespamiento. Su fórmula ligera con Queratina y Lípidos de Avena protege la cutícula y previene daños futuros.",
        howToUse: "Aplicar unas gotas sobre el cabello seco o húmedo, incidiendo en las puntas. No aclarar.",
        stock: 35,
        category: 'hair',
        rating: 4.8,
        reviewCount: 65,
    },
    {
        id: 44961,
        name: "Acondicionador Rico Reparador Duologi",
        brand: "DUOLOGI",
        price: 12.00,
        regularPrice: 16.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44961%2F44961_1.png',
        description: "Acondicionador nutritivo que repara y protege el cabello dañado reduciendo la rotura. Enriquecido con Queratina y Lípidos de Avena para fortalecer la fibra capilar desde el interior.",
        howToUse: "Aplicar sobre el cabello húmedo de medios a puntas después del lavado. Dejar actuar 1-2 minutos y aclarar.",
        stock: 30,
        category: 'hair',
        rating: 4.7,
        reviewCount: 55,
    },
    {
        id: 44965,
        name: "CC Cream Capilar Perfeccionadora 10 en 1 Duologi",
        brand: "DUOLOGI",
        price: 14.50,
        regularPrice: 19.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44965%2F44965_1.png',
        description: "Tratamiento multibeneficio 10 en 1 sin aclarado. Repara, hidrata, protege el color, da brillo, suaviza, controla el encrespamiento, y ofrece protección térmica.",
        howToUse: "Pulverizar sobre el cabello húmedo de medios a puntas antes de peinar. No aclarar.",
        stock: 22,
        category: 'hair',
        rating: 4.9,
        reviewCount: 48,
    },
    {
        id: 43237,
        name: "Corrector y Serum Potenciador Giordani Gold",
        brand: "Giordani Gold",
        price: 7.49,
        regularPrice: 24.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43237%2F43237_1.png',
        description: "Un producto híbrido que combina la cobertura de un corrector con los beneficios de un serum. Ilumina la mirada, disimula imperfecciones y cuida la delicada piel del contorno de ojos.",
        howToUse: "Aplicar una pequeña cantidad sobre las imperfecciones o en la zona de la ojera. Difuminar suavemente con la yema de los dedos, una brocha o una esponja.",
        stock: 45,
        category: 'makeup',
        productType: 'Corrector',
        subCategory: 'Giordani Gold',
        rating: 5,
        reviewCount: 132,
        variants: {
            Tono: [
                { value: 'Light', colorCode: '#F8E4D5', variationId: 4323701 },
                { value: 'Medium', colorCode: '#E6C4B0', variationId: 4323702 },
            ]
        }
    },
    {
        id: 42498,
        name: "Crema Corporal Perfumada Essenza Supreme",
        brand: "Giordani Gold",
        price: 8.49,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42498%2F42498_1.png',
        description: "Una lujosa crema corporal que hidrata profundamente y deja en la piel la sofisticada fragancia floral amaderada de Giordani Gold Essenza Supreme.",
        howToUse: "Masajear generosamente sobre la piel limpia y seca para hidratar y perfumar. Prestar especial atención a las zonas más secas.",
        stock: 50,
        category: 'personal-care',
        rating: 5,
        reviewCount: 105,
    },
    {
        id: 43122,
        name: "Eau de Parfum Nordic Waters for Her",
        brand: "Nordic Waters",
        price: 24.99,
        regularPrice: 42.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43122%2F43122_1.png',
        description: "Una fragancia vibrante y refrescante que captura la esencia de las aguas nórdicas. Con un exclusivo Acorde de Aguas Nórdicas, esencia de limón y pétalos de jazmín.",
        howToUse: "Vaporizar sobre los puntos de pulso: cuello, muñecas e interior de los codos para que la fragancia dure más tiempo.",
        stock: 33,
        category: 'perfume',
        rating: 4.5,
        reviewCount: 45,
    },
    {
        id: 42352,
        name: "Gel Limpiador Refrescante 2 en 1 Novage",
        brand: "NovAge",
        price: 17.99,
        regularPrice: 31.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42352%2F42352_1.png',
        description: "Un gel limpiador 2 en 1 con Vitamina E y Glicerina que limpia y tonifica la piel, dejándola suave, radiante y libre de impurezas. Formulado para todo tipo de pieles.",
        howToUse: "Usar por la mañana y por la noche. Humedecer el rostro, aplicar una pulsación del gel y masajear. Aclarar con abundante agua.",
        stock: 50,
        category: 'skincare',
        rating: 5,
        reviewCount: 95,
    },
    {
        id: 47494,
        name: "Espuma Limpiadora Skinrelief Pro Resilient NovAge",
        brand: "NovAge",
        price: 18.00,
        regularPrice: 32.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47494%2F47494_1.png',
        description: "Espuma limpiadora suave diseñada para pieles sensibles. Calma, limpia y ayuda a fortalecer la barrera cutánea gracias a su tecnología Pro-Resilient.",
        howToUse: "Aplicar una o dos pulsaciones sobre la piel húmeda. Masajear suavemente con movimientos circulares y aclarar con agua tibia.",
        stock: 30,
        category: 'skincare',
        rating: 5,
        reviewCount: 88,
    },
    {
        id: 29696,
        name: "WellnessPack Mujer Wellosophy",
        brand: "Wellosophy",
        price: 45.00,
        regularPrice: 55.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F29696%2F29696.png',
        description: "Cuida tu bienestar integral con WellnessPack Mujer de Wellosophy. Cada sobre diario te aporta una mezcla precisa de 12 vitaminas, 10 minerales, Omega-3 de alta calidad y potentes antioxidantes como la Astaxantina.",
        howToUse: "Tomar el contenido de un sobre al día con la comida principal y un vaso de agua.",
        stock: 20,
        category: 'wellness',
        rating: 5,
        reviewCount: 210,
        beautyPoints: 35,
        isShippingSaver: true,
    },
    {
        id: 44960,
        name: "Mascarilla Capilar Reparadora Intensiva Duologi",
        brand: "DUOLOGI",
        price: 13.00,
        regularPrice: 17.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44960%2F44960.png',
        description: "Transforma tu cabello con el tratamiento intensivo reparador Duologi. Una mascarilla rica que penetra en la fibra capilar con Queratina y Lípidos de Avena para reparar y reducir el daño.",
        howToUse: "Aplicar sobre el cabello seco antes de lavarlo, de medios a puntas. Dejar actuar 5 minutos. Aclarar y proceder con el champú y acondicionador.",
        stock: 25,
        category: 'hair',
        rating: 4.5,
        reviewCount: 45,
    },
    {
        id: 46901,
        name: "Perlas con Serum Giordani Gold - Edición Especial",
        brand: "Giordani Gold",
        price: 21.99,
        regularPrice: 35.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46901%2F46901_1.png",
        description: "Perlas de color con infusión de Sérum rejuvenecedor y Ácido Hialurónico que aportan color, rubor y luminosidad. Cada perla está formada por pigmentos minerales que crean un look natural y radiante. Edición especial con un diseño exclusivo.",
        howToUse: "Desliza la brocha sobre las perlas y aplica sobre los pómulos para un rubor saludable, en la frente y nariz para un efecto bronceado, o en el escote para un toque de luminosidad.",
        stock: 25,
        category: 'makeup',
        productType: 'Colorete y Bronceador',
        subCategory: 'Giordani Gold',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 1,
    },
    {
        id: 47828,
        name: "Brocha Blush & Glow",
        brand: "Vellaperfumeria",
        price: 6.49,
        regularPrice: 11.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47828%2F47828_1.png",
        description: "Brocha de maquillaje de alta calidad, perfecta para aplicar colorete e iluminador. Sus cerdas suaves y su forma angulada permiten una aplicación precisa y un acabado profesional y difuminado.",
        howToUse: "Utiliza la brocha para recoger el producto y aplícalo en los pómulos para dar color, o en los puntos altos del rostro (pómulos, puente de la nariz, arco de cupido) para iluminar.",
        stock: 50,
        category: 'accessories',
        productType: 'Accesorio de Maquillaje',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 86,
    },
    {
        id: 47949,
        name: "Máscara de Pestañas 5 en 1 Wonder Lash Prom Queen THE ONE",
        brand: "THE ONE",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47949%2F47949_1.png",
        description: "La máscara de pestañas 5 en 1 definitiva, ahora en edición especial Prom Queen. Ofrece longitud, volumen, rizo, separación y cuidado en una sola pasada para una mirada de impacto.",
        howToUse: "Aplica desde la raíz hasta las puntas con un movimiento en zigzag para cubrir todas las pestañas. Aplica una segunda capa para mayor volumen e intensidad.",
        stock: 100,
        category: 'makeup',
        productType: 'Máscara',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 878,
    },
    {
        id: 46801,
        name: "Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 27.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png",
        description: "Una fragancia Chipre Floral Amaderada que deja una estela hipnótica y duradera. Las notas de la flor Rubí Scurofloren son el corazón de este aroma sensual y misterioso, perfecto para la noche.",
        howToUse: "Vaporiza la fragancia en los puntos de pulso: cuello, escote y muñecas, para una mayor duración e intensidad.",
        stock: 30,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 26,
    },
    {
        id: 49145,
        name: "Collar Divine Dark Velvet",
        brand: "Divine",
        price: 29.99,
        regularPrice: 41.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F49145%2F49145_1.png",
        description: "Elegante collar de edición limitada inspirado en la fragancia Divine Dark Velvet. Un accesorio sofisticado con detalles en tonos oscuros y dorados para complementar tu look de noche.",
        howToUse: "Ajusta el largo a tu gusto y combínalo con tus prendas favoritas para un toque de elegancia.",
        stock: 15,
        category: 'accessories',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 1,
    },
    {
        id: 48075,
        name: "Muestra Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 1.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48075%2F48075_1.png",
        description: "Descubre la nueva y cautivadora fragancia Divine Dark Velvet. Una muestra perfecta para probar su aroma Chipre Floral Amaderado y decidir si es tu nueva firma olfativa.",
        howToUse: "Aplicar una pequeña cantidad en la muñeca o en el cuello para experimentar la fragancia en tu piel.",
        stock: 100,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 0,
    },
    {
        id: 42041,
        name: "Spray Eau de Parfum Divine - Tamaño Viaje",
        brand: "Divine",
        price: 10.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42041%2F42041_1.png",
        description: "Tu fragancia Divine favorita en un práctico formato de viaje de 8 ml para que la lleves siempre contigo.",
        howToUse: "Vaporizar sobre los puntos de pulso (cuello, muñecas) siempre que desees reavivar la fragancia a lo largo del día.",
        stock: 50,
        category: 'perfume',
        rating: 5,
        reviewCount: 321,
    },
    {
        id: 47016,
        name: "Crema Corporal Perfumada Divine",
        brand: "Divine",
        price: 8.99,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47016%2F47016_1.png",
        description: "Una rica y suntuosa crema corporal que hidrata y nutre la piel en profundidad, dejándola irresistiblemente suave y perfumada con el icónico aroma floral de Divine.",
        howToUse: "Masajear generosamente sobre la piel limpia y seca, preferiblemente después de la ducha o el baño, para una hidratación duradera.",
        stock: 40,
        category: 'personal-care',
        rating: 5,
        reviewCount: 714,
    },
    {
        id: 38497,
        name: "Eau de Parfum Divine",
        brand: "Divine",
        price: 27.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38497%2FES%2F38497_1.png",
        description: "La fragancia floral original de Divine, un clásico atemporal que celebra la feminidad y el poder con sus notas de lirio y freesia. Un aroma que te hace sentir como una diosa.",
        howToUse: "Aplica la fragancia en el cuello, las muñecas y detrás de las orejas para una estela inolvidable que te acompañará todo el día.",
        stock: 35,
        category: 'perfume',
        rating: 5,
        reviewCount: 1953,
    },
    {
        id: 42120,
        name: "Máscara de Pestañas 5 en 1 Wonder Lash Waterproof THE ONE",
        brand: "THE ONE",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42120%2F42120_1.png",
        description: "Todos los beneficios de la máscara 5 en 1, ahora con una fórmula resistente al agua. Ofrece longitud, volumen, rizo, separación y cuidado, con una duración impecable a prueba de agua, sudor y lágrimas.",
        howToUse: "Aplica desde la raíz hasta las puntas con un movimiento de zigzag. Para desmaquillar, utiliza un desmaquillante específico para productos waterproof.",
        stock: 80,
        category: 'makeup',
        productType: 'Máscara',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 841,
    },
    {
        id: 43123,
        name: "Máscara de Pestañas 5 en 1 Wonder Lash Ultra THE ONE",
        brand: "THE ONE",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43123%2F43123_1.png",
        description: "Lleva tus pestañas al siguiente nivel con la máscara de pestañas Ultra. Una fórmula con HD Lash-Lifting Complex que proporciona un volumen, definición y curvatura extremos para un efecto lifting de pestañas al instante.",
        howToUse: "Usa el lado curvo del cepillo para levantar y rizar las pestañas. Usa el lado plano para dar volumen desde la raíz. Aplica varias capas para un efecto más dramático.",
        stock: 75,
        category: 'makeup',
        productType: 'Máscara',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 613,
    },
    {
        id: 46319,
        name: "Niacinamida 10% Power Drops Proceuticals Novage+",
        brand: "Novage+",
        price: 39.99,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46319%2F46319_1.png",
        description: "Tratamiento concentrado con Niacinamida al 10% que minimiza visiblemente los poros, unifica el tono, reduce rojeces y fortalece la barrera cutánea. Una solución potente para una piel más lisa y saludable.",
        howToUse: "Aplicar unas gotas sobre la piel limpia antes del sérum. Usar por la mañana y/o por la noche. Evitar el contorno de ojos.",
        stock: 20,
        category: 'skincare',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 3,
    },
    {
        id: 47267,
        name: "Jabón Líquido con Flor de Loto y Madera de Cedro",
        brand: "Essense&Co.",
        price: 14.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47267%2F47267_1.png",
        description: "Lujoso jabón líquido para manos y cuerpo con una fragancia floral y amaderada. Limpia suavemente sin resecar, dejando la piel hidratada y delicadamente perfumada con notas de flor de loto y madera de cedro.",
        howToUse: "Aplicar sobre la piel húmeda, masajear hasta crear una rica espuma y aclarar con agua. Apto para uso diario.",
        stock: 60,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 141,
    },
    {
        id: 47268,
        name: "Loción Hidratante con Flor de Loto y Madera de Cedro",
        brand: "Essense&Co.",
        price: 15.99,
        regularPrice: 21.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47268%2F47268_1.png",
        description: "Una loción hidratante para manos y cuerpo de rápida absorción que deja la piel suave, nutrida y perfumada con el relajante aroma de flor de loto y madera de cedro.",
        howToUse: "Masajear sobre la piel limpia y seca hasta su completa absorción. Ideal para usar después del Jabón Líquido de la misma línea.",
        stock: 55,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 115,
    },
    {
        id: 153753,
        name: "Lote Essense & Co",
        brand: "Essense&Co.",
        price: 22.99,
        regularPrice: 41.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F153753%2F153753_1.png",
        description: "Un set de lujo para el cuidado de manos y cuerpo que incluye el jabón líquido y la loción hidratante de la línea Essense & Co. El regalo perfecto para una experiencia de spa en casa.",
        howToUse: "Utilizar el jabón líquido para limpiar la piel y seguir con la loción para hidratar y perfumar, creando una experiencia sensorial completa.",
        stock: 25,
        category: 'personal-care',
        tag: 'NOVEDAD',
        statusLabel: 'Set',
        rating: 5,
        reviewCount: 0,
    },
    {
        id: 18437,
        name: "Tratamiento Restaurador de Noche Diamond Cellular",
        brand: "Diamond Cellular",
        price: 24.99,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F18437%2FES%2F18437_1.png",
        description: "Tratamiento de noche de alto rendimiento con Elixir de Diamante™ y Ácido Salicílico. Ayuda a regenerar, rejuvenecer y mejorar la superficie de la piel mientras duermes para un cutis más luminoso por la mañana.",
        howToUse: "Aplicar cada noche sobre la piel limpia del rostro y cuello, evitando el contorno de ojos. Masajear suavemente hasta su completa absorción.",
        stock: 30,
        category: 'skincare',
        rating: 5,
        reviewCount: 1327,
    },
    {
        id: 21339,
        name: "Solución Micelar Diamond Cellular",
        brand: "Diamond Cellular",
        price: 18.99,
        regularPrice: 29.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F21339%2FES%2F21339_1.png",
        description: "Un limpiador multifuncional de lujo. Elimina el maquillaje y las impurezas, tonifica y calma la piel en un solo paso. Con Elixir de Diamante™ y Tecnología Micelar para una piel limpia, fresca y radiante.",
        howToUse: "Aplicar sobre un disco de algodón y pasar suavemente por el rostro, ojos y labios por la mañana y por la noche. No necesita aclarado.",
        stock: 40,
        category: 'skincare',
        rating: 5,
        reviewCount: 1798,
    },
    {
        id: 13659,
        name: "Crema Antienvejecimiento Diamond Cellular",
        brand: "Diamond Cellular",
        price: 28.99,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F13659%2FES%2F13659_1.png",
        description: "Crema de día de lujo que combate los signos del envejecimiento. Formulada con Elixir de Diamante™ y un complejo iluminador para una piel visiblemente más joven, firme y radiante.",
        howToUse: "Aplicar por la mañana sobre la piel limpia del rostro y cuello, evitando la zona de los ojos. Es una base perfecta para el maquillaje.",
        stock: 28,
        category: 'skincare',
        rating: 5,
        reviewCount: 3154,
    },
    {
        id: 47421,
        name: "Espátula de Crema Hidratante Oriflame Exklusiv",
        brand: "Oriflame Exklusiv",
        price: 5.29,
        regularPrice: 6.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47421%2F47421_1.png",
        description: "Una espátula higiénica y reutilizable para aplicar tus cremas faciales. Evita la contaminación del producto al no usar los dedos y permite una aplicación más precisa y uniforme.",
        howToUse: "Utiliza la espátula para coger una pequeña cantidad de tu crema y aplícala en el rostro. Limpiar después de cada uso con agua y jabón.",
        stock: 100,
        category: 'accessories',
        rating: 5,
        reviewCount: 473,
    },
    {
        id: 47005,
        name: "Crema de Día Reafirmante SPF 20 Royal Velvet",
        brand: "Royal Velvet",
        price: 20.99,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47005%2F47005_1.png",
        description: "Una fórmula avanzada con Infusión de Iris Negro™ que reafirma, redefine el contorno facial y reduce la apariencia de arrugas. Con SPF 20 para proteger la piel del fotoenvejecimiento.",
        howToUse: "Aplicar cada mañana sobre la piel limpia del rostro y cuello con un suave masaje ascendente.",
        stock: 35,
        category: 'skincare',
        rating: 5,
        reviewCount: 2161,
    },
    {
        id: 47006,
        name: "Crema de Noche Reafirmante Royal Velvet",
        brand: "Royal Velvet",
        price: 20.99,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47006%2F47006_1.png",
        description: "Trabaja durante la noche para nutrir, fortalecer y reafirmar la piel. La Infusión de Iris Negro™ ayuda a la piel en su proceso de regeneración nocturna, reduciendo la apariencia de arrugas.",
        howToUse: "Aplicar cada noche sobre la piel limpia del rostro y cuello, después del sérum, para potenciar la reparación nocturna.",
        stock: 32,
        category: 'skincare',
        rating: 5,
        reviewCount: 1781,
    },
    {
        id: 47587,
        name: "Pendientes Royal Velvet",
        brand: "Royal Velvet",
        price: 16.99,
        regularPrice: 22.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47587%2F47587_1.png",
        description: "Elegantes pendientes de edición limitada que complementan la lujosa línea de cuidado de la piel Royal Velvet. Un toque final de sofisticación para cualquier look.",
        howToUse: "Accesorio de moda para llevar en las orejas. Evitar el contacto con agua y perfumes para mantener su brillo.",
        stock: 20,
        category: 'accessories',
        rating: 4.5,
        reviewCount: 19,
    },
    {
        id: 46906,
        name: 'Maquillaje Stress-Free Everlasting Sync SPF 20 + Protección UVA Natural THE ONE',
        brand: 'The ONE',
        price: 9.23,
        regularPrice: 20.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46906%2F46906_1.png',
        description: 'Maquillaje de larga duración que se adapta a las necesidades de tu piel, con SPF 20 y protección UVA. Acabado natural y sin estrés.',
        stock: 30,
        category: 'makeup',
        productType: 'Base',
        rating: 4.8,
        reviewCount: 936,
        variants: {
            Tono: [
                { value: 'Pale Ivory', colorCode: '#F9E0CF', variationId: 4690601 },
                { value: 'Vanilla', colorCode: '#F9E5CC', variationId: 4690602 },
                { value: 'Porcelain', colorCode: '#EACFBC', variationId: 4690603 },
                { value: 'Marble', colorCode: '#EAD0B6', variationId: 4690604 },
                { value: 'Light Rose', colorCode: '#EAD0C0', variationId: 4690605 },
                { value: 'Light Beige', colorCode: '#E0C0A5', variationId: 4690606 },
                { value: 'Soft Sand', colorCode: '#DFB8AA', variationId: 4690607 },
                { value: 'Beige Warm', colorCode: '#D7BAA4', variationId: 4690608 },
                { value: 'Natural Beige', colorCode: '#D7B4A4', variationId: 4690609 },
                { value: 'Sienna', colorCode: '#C19674', variationId: 4690610 },
                { value: 'Toast', colorCode: '#B27E5C', variationId: 4690611 },
                { value: 'Hazelnut', colorCode: '#8B6555', variationId: 4690612 },
            ]
        }
    },
    {
        id: 42236,
        name: 'Maquillaje Antienvejecimiento Serum Boost SPF 12 + Protección UVA Giordani Gold',
        brand: 'Giordani Gold',
        price: 13.08,
        regularPrice: 31.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42236%2F42236_1.png',
        description: 'Un maquillaje con serum que combate los signos del envejecimiento, hidrata y protege la piel con SPF 12.',
        stock: 25,
        category: 'makeup',
        productType: 'Base',
        rating: 4.8,
        reviewCount: 1421,
        variants: {
            Tono: [
                { value: 'Vanilla Neutral', colorCode: '#F4D7B3', variationId: 4223601 },
                { value: 'Vanilla Cool', colorCode: '#F7D5BB', variationId: 4223602 },
                { value: 'Porcelain Warm', colorCode: '#EEC9B4', variationId: 4223603 },
                { value: 'Light Beige Neutral', colorCode: '#F0CAAA', variationId: 4223604 },
                { value: 'Light Ivory Neutral', colorCode: '#E1AE8F', variationId: 4223605 },
                { value: 'Beige Warm', colorCode: '#D2A282', variationId: 4223606 },
            ]
        }
    },
    {
        id: 43244,
        name: 'Maquillaje Eternal Glow SPF 25 Giordani Gold',
        brand: 'Giordani Gold',
        price: 13.85,
        regularPrice: 32.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43244%2FES%2F43244_1.png',
        description: 'Maquillaje con acabado luminoso y SPF 25 que proporciona un brillo eterno y una piel de aspecto más joven.',
        stock: 20,
        category: 'makeup',
        productType: 'Base',
        rating: 4.8,
        reviewCount: 954,
         variants: {
            Tono: [
                { value: 'Vanilla Neutral', colorCode: '#F9DFBF', variationId: 4324401 },
                { value: 'Porcelain Warm', colorCode: '#E6C59D', variationId: 4324402 },
                { value: 'Light Beige Neutral', colorCode: '#E6C095', variationId: 4324403 },
                { value: 'Soft Sand', colorCode: '#E6BB95', variationId: 4324404 },
                { value: 'Ivory Neutral', colorCode: '#D9B08D', variationId: 4324405 },
                { value: 'Natural Beige', colorCode: '#D2A282', variationId: 4324406 },
                { value: 'Beige Warm', colorCode: '#C59A7D', variationId: 4324407 },
            ]
        }
    },
    {
        id: 32922,
        name: 'Maquillaje Liquid Silk Giordani Gold',
        brand: 'Giordani Gold',
        price: 23.87,
        regularPrice: 30.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F32922%2FES%2F32922_1.png',
        description: 'Base de maquillaje fluida y ligera con acabado de seda para una cobertura perfecta y natural.',
        stock: 15,
        category: 'makeup',
        productType: 'Base',
        rating: 4.8,
        reviewCount: 1973,
         variants: {
            Tono: [
                { value: 'Vanilla', colorCode: '#E8C396', variationId: 3292201 },
                { value: 'Porcelain', colorCode: '#E9CAAD', variationId: 3292202 },
                { value: 'Light Ivory', colorCode: '#DABD9F', variationId: 3292203 },
                { value: 'Natural Beige', colorCode: '#B38659', variationId: 3292204 },
                { value: 'Amber', colorCode: '#B58D6A', variationId: 3292205 },
            ]
        }
    },
    {
        id: 46332,
        name: 'Maquillaje Illuskin Glow Reflective THE ONE',
        brand: 'The ONE',
        price: 15.40,
        regularPrice: 20.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46332%2F46332_1.png',
        description: 'Maquillaje que refleja la luz para un brillo natural y una piel visiblemente más saludable.',
        stock: 35,
        category: 'makeup',
        productType: 'Base',
        rating: 4.7,
        reviewCount: 572,
        variants: {
            Tono: [
                { value: 'Vanilla Neutral', colorCode: '#F9DFBF', variationId: 4633201 },
                { value: 'Marble Neutral', colorCode: '#E8C9A7', variationId: 4633202 },
                { value: 'Porcelain Cool', colorCode: '#FDE3D8', variationId: 4633203 },
                { value: 'Light Ivory Neutral', colorCode: '#E6C095', variationId: 4633204 },
                { value: 'Beige Neutral', colorCode: '#D5AC96', variationId: 4633205 },
                { value: 'Beige Warm', colorCode: '#D9AA88', variationId: 4633206 },
            ]
        }
    },
    {
        id: 42102,
        name: 'Maquillaje Mineral de Larga Duración SPF 20 Giordani Gold',
        brand: 'Giordani Gold',
        price: 23.87,
        regularPrice: 30.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42102%2F42102_1.png',
        description: 'Base de maquillaje con minerales volcánicos para una cobertura duradera y un acabado impecable. Con SPF 20.',
        stock: 18,
        category: 'makeup',
        productType: 'Base',
        rating: 4.8,
        reviewCount: 1004,
         variants: {
            Tono: [
                { value: 'Vanilla Neutral', colorCode: '#F9DFBF', variationId: 4210201 },
                { value: 'Porcelain Warm', colorCode: '#E6C59D', variationId: 4210202 },
                { value: 'Marble Neutral', colorCode: '#E8C9A7', variationId: 4210203 },
                { value: 'Light Beige Neutral', colorCode: '#E6C095', variationId: 4210204 },
                { value: 'Soft Sand', colorCode: '#F2C6A9', variationId: 4210205 },
                { value: 'Light Ivory Neutral', colorCode: '#D5AC96', variationId: 4210206 },
                { value: 'Natural Beige', colorCode: '#D2A282', variationId: 4210207 },
            ]
        }
    },
    {
        id: 39292,
        name: 'Crema Iluminadora Peach OnColour',
        brand: 'OnColour',
        price: 8.47,
        regularPrice: 12.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F39292%2F39292_1.png',
        description: 'Crema iluminadora con un toque de color melocotón para un brillo saludable y natural.',
        stock: 50,
        category: 'makeup',
        productType: 'Base',
        rating: 4.8,
        reviewCount: 564,
    },
    {
        id: 42125,
        name: 'Maquillaje Semi-Mate Everlasting Sync SPF 10 + Protección UVA THE ONE',
        brand: 'The ONE',
        price: 15.40,
        regularPrice: 20.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42125%2F42125_1.png',
        description: 'Base de maquillaje con acabado semi-mate que se sincroniza con tu piel. Larga duración y protección SPF 10.',
        stock: 40,
        category: 'makeup',
        productType: 'Base',
        rating: 4.6,
        reviewCount: 639,
        variants: {
            Tono: [
                { value: 'Alabaster Cool', colorCode: '#E5BEAA', variationId: 4212501 },
                { value: 'Vanilla Neutral', colorCode: '#EBCAAB', variationId: 4212502 },
                { value: 'Porcelain Cool', colorCode: '#FAC9AA', variationId: 4212503 },
                { value: 'Beige Neutral', colorCode: '#DAAD87', variationId: 4212504 },
                { value: 'Ivory Neutral', colorCode: '#CBA077', variationId: 4212505 },
                { value: 'Beige Warm', colorCode: '#CEA17C', variationId: 4212506 },
                { value: 'Sun Beige Warm', colorCode: '#D9A170', variationId: 4212507 },
                { value: 'Amber Warm', colorCode: '#BC8055', variationId: 4212508 },
                { value: 'Caramel Warm', colorCode: '#AB693E', variationId: 4212509 },
                { value: 'Chestnut Warm', colorCode: '#835535', variationId: 4212510 },
            ]
        }
    },
    {
        id: 47551,
        name: 'Esponjilla de Maquillaje de Silicona Hidden Gems',
        brand: 'Vellaperfumeria',
        price: 2.69,
        regularPrice: 8.99,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47551%2F47551_1.png',
        description: 'Esponja de silicona para una aplicación de maquillaje higiénica y sin desperdicio de producto.',
        stock: 100,
        category: 'makeup',
        productType: 'Accesorio de Maquillaje',
        rating: 4.7,
        reviewCount: 36,
    },
    {
        id: 46134,
        name: 'BB Cream Beautifier MAX SPF 15 THE ONE',
        brand: 'The ONE',
        price: 17.00,
        regularPrice: 22.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46134%2F46134_1.png',
        description: 'Una BB cream multifuncional que hidrata, unifica el tono, protege con SPF 15 y proporciona un acabado natural y radiante. Perfecta para el día a día.',
        stock: 40,
        category: 'makeup',
        productType: 'Cremas BB y CC',
        rating: 4.8,
        reviewCount: 232,
        tag: 'NOVEDAD',
        variants: { Tono: [
          { value: 'Light', colorCode: '#F5D3B8', variationId: 4613401 },
          { value: 'Fair', colorCode: '#EBC7A9', variationId: 4613402 },
          { value: 'Medium', colorCode: '#D8B18E', variationId: 4613403 },
          { value: 'Dark', colorCode: '#C49871', variationId: 4613404 },
        ]}
    },
    {
        id: 35641,
        name: 'Bálsamo BB Cream OnColour',
        brand: 'OnColour',
        price: 3.99,
        regularPrice: 10.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F35641%2F35641_1.png',
        description: 'Un bálsamo ligero con color que hidrata y perfecciona la piel al instante. Proporciona una cobertura ligera para un look fresco y natural.',
        stock: 60,
        category: 'makeup',
        productType: 'Cremas BB y CC',
        rating: 4.8,
        reviewCount: 686,
        variants: { Tono: [
          { value: 'Light', colorCode: '#F4D9C3', variationId: 3564101 },
          { value: 'Medium', colorCode: '#E3C1A6', variationId: 3564102 },
          { value: 'Dark', colorCode: '#D3A989', variationId: 3564103 },
        ]}
    },
    {
        id: 42113,
        name: 'Crema Correctora del Color SPF 30 + Protección UVA Giordani Gold',
        brand: 'Giordani Gold',
        price: 30.00,
        regularPrice: 38.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42113%2F42113_1.png',
        description: 'Una lujosa CC cream que combina maquillaje y tratamiento. Corrige el tono, ilumina, hidrata y protege del sol con SPF 30 y protección UVA.',
        stock: 35,
        category: 'makeup',
        productType: 'Cremas BB y CC',
        rating: 4.8,
        reviewCount: 369,
        variants: { Tono: [
          { value: 'Light', colorCode: '#F2D3B8', variationId: 4211301 },
          { value: 'Medium', colorCode: '#E7BE9D', variationId: 4211302 },
        ]}
    },
    {
        id: 40769,
        name: 'Colorete Marmoleado THE ONE',
        brand: 'The ONE',
        price: 9.99,
        regularPrice: 18.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F40769%2F40769.png',
        description: 'Colorete marmoleado de alta pigmentación para un acabado radiante y multidimensional. Fórmula sedosa que se difumina fácilmente.',
        stock: 50,
        category: 'makeup',
        productType: 'Colorete y Bronceador',
        rating: 4.9,
        reviewCount: 451,
        variants: { Tono: [
          { value: 'Pink', colorCode: '#E6A4B4', variationId: 4076901 },
          { value: 'Coral', colorCode: '#F4B08B', variationId: 4076902 },
        ]}
    },
    {
        id: 38810,
        name: 'Colorete OnColour',
        brand: 'OnColour',
        price: 4.99,
        regularPrice: 11.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38810%2F38810.png',
        description: 'Un colorete vibrante y fácil de usar para un toque de color saludable en tus mejillas. Disponible en tonos favorecedores para todos los looks.',
        stock: 80,
        category: 'makeup',
        productType: 'Colorete y Bronceador',
        rating: 4.7,
        reviewCount: 723,
        variants: { Tono: [
          { value: 'Cool Pink', colorCode: '#F7C8E0', variationId: 3881001 },
          { value: 'Coral Pink', colorCode: '#FFAACF', variationId: 3881002 },
        ]}
    },
    {
        id: 47000,
        name: 'Perlas Bronceadoras Radiant Giordani Gold',
        brand: 'Giordani Gold',
        price: 19.99,
        regularPrice: 35.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47000%2F47000.png',
        description: 'Las icónicas perlas bronceadoras ahora con una fórmula mejorada para un brillo aún más radiante. Hechas a mano en Italia, combinan color y luminosidad.',
        stock: 40,
        category: 'makeup',
        productType: 'Colorete y Bronceador',
        rating: 4.9,
        reviewCount: 2588,
        variants: { Tono: [
          { value: 'Natural Radiance', colorCode: '#D9A170', variationId: 4700001 },
          { value: 'Luminous Peach', colorCode: '#E5B099', variationId: 4700002 },
        ]}
    },
    {
        id: 42121,
        name: 'Paleta de Ojos y Rostro Fabulous Beauty Giordani Gold',
        brand: 'Giordani Gold',
        price: 29.99,
        regularPrice: 42.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42121%2F42121_1.png',
        description: 'Una lujosa paleta todo en uno que contiene sombras de ojos, colorete, bronceador e iluminador. Perfecta para crear looks completos y sofisticados en cualquier momento.',
        stock: 25,
        category: 'makeup',
        productType: 'Colorete y Bronceador',
        rating: 4.8,
        reviewCount: 344,
    },
    {
        id: 46940,
        name: 'Stick Iluminador con Color THE ONE',
        brand: 'The ONE',
        price: 22.00,
        regularPrice: 28.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46940%2F46940_1.png',
        description: 'Un stick cremoso y multifuncional que se desliza sin esfuerzo para aportar un toque de color y un brillo luminoso a mejillas, labios y ojos. Fórmula fácil de difuminar.',
        stock: 50,
        category: 'makeup',
        productType: 'Colorete y Bronceador',
        rating: 4.8,
        reviewCount: 510,
        tag: 'NOVEDAD',
        variants: { Tono: [
            { value: 'Sparkling Rose', colorCode: '#F8B195', variationId: 4694001 },
            { value: 'Glimmering Peach', colorCode: '#F67280', variationId: 4694002 },
            { value: 'Dazzling Berry', colorCode: '#C06C84', variationId: 4694003 },
            { value: 'Radiant Bronze', colorCode: '#6C5B7B', variationId: 4694004 },
        ]}
    },
    {
        id: 44917,
        name: 'Perlas con Serum Giordani Gold',
        brand: 'Giordani Gold',
        price: 35.00,
        regularPrice: 42.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44917%2F44917_1.png',
        description: 'Las icónicas perlas de Giordani Gold, ahora con una infusión de serum para cuidar la piel mientras aportan un color radiante y un acabado luminoso.',
        stock: 30,
        category: 'makeup',
        productType: 'Colorete y Bronceador',
        rating: 4.8,
        reviewCount: 1466,
        variants: { Tono: [
            { value: 'Sublime Radiance', colorCode: '#EACDC2', variationId: 4491701 },
            { value: 'Luminous Peach', colorCode: '#E4B699', variationId: 4491702 },
            { value: 'Golden Bronze', colorCode: '#D6A07D', variationId: 4491703 },
            { value: 'Matte Bronze', colorCode: '#C88A61', variationId: 4491704 },
        ]}
    },
    // New products
    {
        id: 29697,
        name: "WellnessPack Hombre Wellosophy",
        brand: "Wellosophy",
        price: 45.00,
        regularPrice: 55.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F29697%2F29697.png',
        description: "Una combinación equilibrada de 12 vitaminas y 10 minerales, ácidos grasos Omega-3, extracto de arándano y microalgas que contienen el carotenoide Astaxantina. Desarrollado para las necesidades del hombre.",
        stock: 25,
        category: 'wellness',
        rating: 5,
        reviewCount: 180,
        beautyPoints: 35,
        isShippingSaver: true,
    },
    {
        id: 47442,
        name: "Batido Sustitutivo de Comida Wellosophy (Chocolate)",
        brand: "Wellosophy",
        price: 50.00,
        regularPrice: 60.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47442%2F47442.png',
        description: "Un batido delicioso y nutritivo para sustituir una comida, sabor chocolate. Alto en proteínas y fibra, con 23 vitaminas y minerales esenciales para ayudarte a controlar tu peso de forma saludable.",
        stock: 15,
        category: 'wellness',
        rating: 4.9,
        reviewCount: 95,
        beautyPoints: 40,
        isShippingSaver: true,
    },
    {
        id: 32002,
        name: "Limpiador y Exfoliante North for Men Subzero",
        brand: "North for Men",
        price: 14.00,
        regularPrice: 18.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F32002%2F32002.png',
        description: "Limpiador facial 2 en 1 para hombre que purifica y exfolia la piel. Formulado con raíz ártica y tecnología Pro Defence para una piel revitalizada, fresca y llena de energía.",
        stock: 50,
        category: 'men',
        rating: 4.9,
        reviewCount: 450,
    },
];
