

import type { Product } from './types';

export const allProducts: Product[] = [
    // Existing products from previous OfertasPage, with updated images
    {
        id: 101,
        name: "Bálsamo BB Cream OnColour",
        brand: "OnColour",
        price: 5.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_101_oncolour_bb_cream_oriflame_v2.jpg",
        description: "Logra un look impecable al instante con el Bálsamo BB Cream OnColour. Esta crema multifunción 8 en 1 con SPF 10 hidrata, protege y perfecciona tu piel. Su fórmula ligera unifica el tono, disimula imperfecciones y aporta un acabado natural y radiante. Es el todo en uno que necesitas para lucir una piel fresca y saludable cada día.",
        stock: 50,
        category: 'makeup',
        subCategory: 'OnColour',
        rating: 4,
        reviewCount: 88,
        isShippingSaver: true,
    },
    {
        id: 102,
        name: "Maquillaje Everlasting Sync SPF 20",
        brand: "THE ONE",
        price: 15.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_102_the_one_everlasting_sync_oriflame_v2.jpg",
        description: "Descubre el maquillaje inteligente que se sincroniza con tu piel. La Base Everlasting Sync SPF 20 de THE ONE, con Tecnología Skin Response, se adapta a la humedad del ambiente para un acabado fresco y semi-mate que dura hasta 30 horas. Ofrece una cobertura media-alta y protección UVA, asegurando un look perfecto y equilibrado todo el día.",
        stock: 30,
        category: 'makeup',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 150,
        variants: {
            "Tono": [
                { value: 'Light Sand', colorCode: '#f0d3b9' },
                { value: 'Ivory', colorCode: '#f9e6d0' },
                { value: 'Beige', colorCode: '#e0b998' },
                { value: 'Sun Beige', colorCode: '#d2a37d' }
            ]
        }
    },
    {
        id: 103,
        name: "Pre-Champú Reparador Duologi",
        brand: "DUOLOGI",
        price: 10.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_103_duologi_pre_shampoo_oriflame_v2.jpg",
        description: "Transforma tu cabello con el Pre-Champú Reparador Duologi. Este tratamiento intensivo prelavado penetra en la fibra capilar para reparar y reducir el daño visible desde la primera aplicación. Su fórmula sin siliconas fortalece y protege, dejando tu cabello listo para un lavado que revela una melena renovada, suave y saludable.",
        stock: 25,
        category: 'hair',
        rating: 4,
        reviewCount: 45,
    },
    {
        id: 104,
        name: "WellnessPack Mujer Wellosophy",
        brand: "Wellosophy",
        price: 42.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_104_wellness_pack_woman_oriflame_v2.jpg",
        description: "Cuida tu bienestar integral con WellnessPack Mujer de Wellosophy. Cada sobre diario te aporta una mezcla precisa de 12 vitaminas, 10 minerales, Omega-3 de alta calidad y potentes antioxidantes como la Astaxantina. Un complemento diseñado para fortalecer tu sistema inmunitario, potenciar tu energía y realzar la belleza de tu piel desde el interior.",
        stock: 20,
        category: 'wellness',
        rating: 5,
        reviewCount: 210,
    },
    {
        id: 105,
        name: "Crema de Noche Reafirmante Royal Velvet",
        brand: "Royal Velvet",
        price: 37.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_105_royal_velvet_night_cream_oriflame_v2.jpg",
        description: "Revitaliza tu piel mientras duermes con la Crema de Noche Reafirmante Royal Velvet. Enriquecida con Infusión de Iris Negro, esta lujosa crema fortalece la matriz de la piel, mejora la elasticidad y redefine el contorno facial noche tras noche. Despierta con un rostro visiblemente más firme, suave y rejuvenecido.",
        stock: 15,
        category: 'skincare',
        rating: 5,
        reviewCount: 95,
    },
    {
        id: 106,
        name: "Eau de Parfum Love Potion",
        brand: "Oriflame",
        price: 38.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_106_love_potion_oriflame_v2.jpg",
        description: "Despierta la pasión con el Eau de Parfum Love Potion, una adictiva fragancia oriental. Sus notas de jengibre especiado, flor de cacao y chocolate crean un elixir irresistible que te envuelve en un aura de seducción. El aroma perfecto para explorar tus deseos más profundos y vivir momentos inolvidables.",
        stock: 18,
        category: 'perfume',
        rating: 4,
        reviewCount: 123,
    },
    {
        id: 107,
        name: "Mascarilla Nocturna Novage+",
        brand: "NOVAGE+",
        price: 34.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_107_novage_mask_oriflame_v2.jpg",
        description: "Recarga tu piel durante la noche con la Mascarilla Nocturna Novage+. Su fórmula intensiva con Ácido Hialurónico y aceite Inca Inchi hidrata en profundidad, fortalece la barrera cutánea y combate los signos de fatiga. Despierta con una piel visiblemente descansada, revitalizada y luminosa.",
        stock: 22,
        category: 'skincare',
        rating: 5,
        reviewCount: 78,
    },
    {
        id: 108,
        name: "Polvos Compactos con Serum Giordani Gold",
        brand: "GIORDANI GOLD",
        price: 21.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_108_giordani_powder_oriflame_v2.jpg",
        description: "Unifica y perfecciona tu tez con los Polvos Compactos con Serum de Giordani Gold. Su fórmula innovadora combina pigmentos de alta definición con un Serum Rejuvenecedor y Ácido Hialurónico. El resultado es un acabado sedoso y luminoso que cuida tu piel y la protege con SPF. El lujo y el tratamiento se unen en un solo producto.",
        stock: 35,
        category: 'makeup',
        subCategory: 'Giordani Gold',
        rating: 4,
        reviewCount: 65,
    },
    {
        id: 109,
        name: "Crema Reparadora Talones Agrietados Feet Up",
        brand: "Feet Up Expert",
        price: 10.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_109_feet_up_heel_repair_oriflame_v2.jpg",
        description: "Dile adiós a los talones agrietados con la Crema Reparadora Feet Up Expert. Con resultados visibles en solo 3 días, su fórmula con Urea al 10% y tecnología Pro-Barrier hidrata intensamente, repara las fisuras y restaura la suavidad de la piel. Un cuidado profesional para unos pies sanos y bonitos.",
        stock: 40,
        category: 'personal-care',
        rating: 5,
        reviewCount: 195,
        isShippingSaver: true,
    },
     {
        id: 110,
        name: "Acondicionador Suavizante Miel y Leche",
        brand: "Milk & Honey Gold",
        price: 8.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_110_milk_honey_conditioner_oriflame_v2.jpg",
        description: "Envuelve tu cabello en la riqueza del Acondicionador Milk & Honey Gold. Su fórmula cremosa, con extractos orgánicos de leche y miel, nutre, suaviza y desenreda al instante. Ideal para cabello seco, lo deja manejable, sedoso y delicadamente perfumado. Un verdadero placer para tus sentidos y tu melena.",
        stock: 30,
        category: 'hair',
        rating: 4,
        reviewCount: 77,
    },
    {
        id: 111,
        name: "Champú Suavizante Miel y Leche",
        brand: "Milk & Honey Gold",
        price: 8.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_111_milk_honey_shampoo_oriflame_v2.jpg",
        description: "Disfruta de una limpieza lujosa con el Champú Milk & Honey Gold. Formulado con extractos orgánicos de leche y miel, hidrata y nutre intensamente, devolviendo el brillo y la suavidad al cabello seco. Su espuma rica y cremosa limpia con delicadeza, dejando una melena radiante y perfumada.",
        stock: 30,
        category: 'hair',
        rating: 4,
        reviewCount: 82,
    },
    {
        id: 112,
        name: "Champú Matizador Duologi",
        brand: "DUOLOGI",
        price: 14.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_112_duologi_purple_shampoo_oriflame_v2.jpg",
        description: "Mantén tu rubio perfecto con el Champú Matizador Duologi. Sus pigmentos violetas neutralizan al instante los tonos amarillentos y anaranjados no deseados en cabellos rubios, con mechas o grises. Enriquecido con Aminoácidos de Seda, deja el cabello suave, brillante y con un color vibrante y renovado.",
        stock: 20,
        category: 'hair',
        rating: 5,
        reviewCount: 35,
    },
    // New products from images
    {
        id: 201,
        name: "Eau de Parfum Eclat Nuit para Ella",
        brand: "Eclat",
        price: 43.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_201_eclat_nuit_oriflame_v2.jpg",
        description: "Captura la esencia de una noche en París con Eclat Nuit para Ella. Este sofisticado perfume Chipre floral combina la intensidad del pachulí con un corazón de rosa y jazmín. Una fragancia cautivadora y duradera que deja una estela de elegancia y misterio a tu paso.",
        stock: 25,
        category: 'perfume',
        rating: 5,
        reviewCount: 40,
    },
    {
        id: 202,
        name: "Limpiador en Aceite Novage+",
        brand: "NOVAGE+",
        price: 30.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_202_novage_oil_cleanser_oriflame_v2.jpg",
        description: "Eleva tu limpieza facial al siguiente nivel con el Limpiador en Aceite Novage+. Este lujoso aceite se transforma en una emulsión lechosa que disuelve maquillaje, protector solar e impurezas. Su sistema Bio Lipid nutre y protege la barrera cutánea, dejando la piel impecablemente limpia, suave y confortable.",
        stock: 30,
        category: 'skincare',
        rating: 5,
        reviewCount: 60,
    },
    {
        id: 203,
        name: "Mascarilla y Exfoliante 2 en 1 Love Nature",
        brand: "Love Nature",
        price: 7.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_203_love_nature_mask_oriflame_v2.jpg",
        description: "Combate las imperfecciones con el tratamiento 2 en 1 de Love Nature. Con árbol de té y lima orgánicos, úsalo como exfoliante para suavizar la piel o como mascarilla para purificar y controlar los brillos. La solución perfecta para una piel grasa, dejándola matificada, clara y fresca.",
        stock: 45,
        category: 'skincare',
        rating: 4,
        reviewCount: 110,
    },
    {
        id: 204,
        name: "Sérum Antiarrugas Novage+",
        brand: "NOVAGE+",
        price: 60.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_204_novage_serum_oriflame_v2.jpg",
        description: "Revierte los signos del tiempo con el Sérum Antiarrugas Novage+. Su avanzada tecnología Bio CollagenPro y Orpéptido-3 estimula la producción de colágeno, reduciendo visiblemente arrugas y líneas de expresión. Consigue una piel más lisa, firme y de aspecto visiblemente más joven.",
        stock: 20,
        category: 'skincare',
        rating: 5,
        reviewCount: 85,
    },
    {
        id: 205,
        name: "Desodorante Roll-On Perfumado Miss Giordani",
        brand: "Giordani Gold",
        price: 5.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_205_miss_giordani_rollon_oriflame_v2.jpg",
        description: "Siente la frescura y elegancia de Miss Giordani durante todo el día. Este desodorante roll-on te protege eficazmente mientras te perfuma con las vibrantes notas de neroli y mango. Una protección duradera con un toque de sofisticación italiana.",
        stock: 50,
        category: 'personal-care',
        rating: 4,
        reviewCount: 92,
        isShippingSaver: true,
    },
    {
        id: 206,
        name: "Aceite Facial Purificante Love Nature",
        brand: "Love Nature",
        price: 9.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_206_love_nature_oil_oriflame_v2.jpg",
        description: "Equilibra tu piel grasa con el Aceite Facial Purificante Love Nature. Formulado con árbol de té y lima orgánicos, este aceite ligero calma las imperfecciones, controla el exceso de sebo y purifica la piel sin obstruir los poros. Unas pocas gotas para un rostro matificado, claro y confortable.",
        stock: 35,
        category: 'skincare',
        rating: 4,
        reviewCount: 75,
    },
    {
        id: 207,
        name: "Champú Anticaída Duologi",
        brand: "DUOLOGI",
        price: 13.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_207_duologi_anticaida_shampoo_oriflame_v2.jpg",
        description: "Lucha contra la caída del cabello con el Champú Anticaída Duologi. Su fórmula con Niacinamida y Proteína de Queratina fortalece el cabello desde la raíz, mejora la densidad y promueve un crecimiento saludable. Para una melena más fuerte, abundante y resistente.",
        stock: 15,
        category: 'hair',
        rating: 5,
        reviewCount: 50,
    },
    // Products added for catalog
    {
        id: 214,
        name: "Lote Experto Antienvejecimiento Novage+",
        brand: "NOVAGE+",
        price: 225.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_214_novage_set_oriflame_v2.jpg",
        description: "Descubre el poder antienvejecimiento con la rutina completa Novage+. Este lote experto incluye limpiador, contorno de ojos, sérum y cremas de día y noche, formulados con tecnologías avanzadas para combatir arrugas, flacidez y falta de luminosidad. Una piel visiblemente más joven y radiante en 4 pasos.",
        stock: 15,
        category: 'skincare',
        tag: 'SET',
    },
    {
        id: 46901,
        name: "Perlas con Serum Giordani Gold - Edición Especial",
        brand: "GIORDANI GOLD",
        price: 32.00,
        imageUrl: "https://storage.googleapis.com/aistudio-public/gallery/product_46901_giordani_pearls_oriflame_v2.jpg",
        description: "Las icónicas Perlas de Giordani Gold se visten de gala en el tono Cherry Touch. Estas perlas de edición especial, infusionadas con Serum Rejuvenecedor, aportan un rubor radiante y saludable con un acabado aterciopelado. El toque final perfecto para un look sofisticado y luminoso.",
        stock: 30,
        category: 'makeup',
    }
];